### ISSUE TITLE
export course

### ISSUE THREAD

**Issue by laithmassoud** [Abstract-Tech/derex.runner#5]
**The Studio servers encountered an error**
An error occurred in Studio and the page could not be loaded. Please try again in a few moments. We've logged the error and our staff is currently working to resolve this error as soon as possible. If the problem persists, please email us at technical@example.com.

```
Traceback (most recent call last):


  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner


    response = get_response(request)


  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response


    response = self._get_response(request)


  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response


    response = self.process_exception_by_middleware(e, request)


  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response


    response = wrapped_callback(request, *callback_args, **callback_kwargs)


  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/http.py", line 40, in inner


    return func(request, *args, **kwargs)


  File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view


    response = view_func(request, *args, **kwargs)


  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view


    return view_func(request, *args, **kwargs)


  File "/openedx/edx-platform/common/djangoapps/util/views.py", line 49, in inner


    response = view_func(request, *args, **kwargs)


  File "/openedx/edx-platform/cms/djangoapps/contentstore/views/import_export.py", line 427, in export_output_handler


    tarball = course_import_export_storage.open(artifact.file.name)


  File "/usr/local/lib/python2.7/site-packages/django/core/files/storage.py", line 38, in open


    return self._open(name, mode)


  File "/usr/local/lib/python2.7/site-packages/django/core/files/storage.py", line 300, in _open


    return File(open(self.path(name), mode))


IOError: [Errno 2] No such file or directory: u'/edx/var/edxapp/media/user_tasks/2019/07/04/course.iO3AjE.tar.gz' ```

**Comment by silviot** [comment]
THe fixes to the celery workers should fix this.
